name: Daily Commit

on:
  schedule:
    - cron: '30 5 * * *'  # Runs daily at 5:30 UTC
  workflow_dispatch:       # Optional: lets you run manually from GitHub UI

jobs:
  commit-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}   # ✅ Enables write access

      - name: Set up Git identity (23f3003877@ds.study.iitm.ac.in)
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "23f3003877@ds.study.iitm.ac.in"

      - name: Make a file change
        run: |
          echo "Run at $(date)" >> daily-log.txt

      - name: Commit and push
        run: |
          git add daily-log.txt
          git commit -m "Daily update - $(date)" || echo "No changes to commit"
          git push origin HEAD
